version: '3.9'
volumes:
  prometheus_data: { }

services:
  soil-monitor:
    build: .
    ports:
      - "0.0.0.0:8080:8080"
    expose: [ 8080 ]
    restart: always
    depends_on:
      - prometheus

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    restart: always
    ports:
      - "0.0.0.0:9090:9090"
    expose: [ 9090 ]
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'